import type { EnglishModule, EnglishText } from '../../lib/content/english'

/**
 * Module B: Critical Study of Literature — the Poetry of T.S. Eliot.
 * Confirmed as the real prescribed poet from the user's own course notes
 * ("Seb M - English HSC .pdf"), which quote all five poems below in full —
 * every quote here was checked against that direct quotation, not memory.
 * All five poems predate 1929 (1915-1927), so they're safely quotable at
 * length for educational analysis regardless of copyright status.
 *
 * Critical framings below (Grover Smith, F.R. Leavis, Barbour) are referred
 * to in general terms rather than quoted verbatim in quotation marks — the
 * user's notes paraphrase these critics rather than citing an exact
 * sentence, and this project only presents something as a verified direct
 * quote when it has actually been checked against that exact source.
 */

export const MODULE_B: EnglishModule = {
  id: 'module-b',
  name: 'Module B: Critical Study of Literature',
  yearLevel: 12,
  syllabusOverviewHtml:
    'Students develop detailed analytical and critical understanding of a single, substantial body of literary work, building an increasingly personal and well-supported response to it over the course of close study. They study a prescribed text (or, as here, a prescribed body of poetry by one writer), closely analysing its construction, content and language, considering the context of its composition and reception, and using their own research and reading to develop an informed, well-evidenced interpretation of its ideas and significance.',
  textIds: ['eliot-poetry'],
}

export const ELIOT_POETRY: EnglishText = {
  id: 'eliot-poetry',
  moduleId: 'module-b',
  title: 'Selected Poems of T.S. Eliot',
  author: 'T.S. Eliot',
  form: 'poetry',
  publicationInfo:
    '"The Love Song of J. Alfred Prufrock" (written 1910-11, published 1915, collected 1917); "Preludes" and "Rhapsody on a Windy Night" (1917); "The Hollow Men" (1925); "Journey of the Magi" (1927)',
  overviewHtml:
    'Five poems spanning Eliot\'s early and middle career, read as a critical study of a single body of work rather than five isolated texts. Taken together, they trace an arc: "Prufrock" and "Preludes"/"Rhapsody" diagnose the paralysis, alienation and spiritual emptiness of modern urban life through fragmented, dramatic-monologue and impressionistic forms; "The Hollow Men" extends that diagnosis to a post-war collective; "Journey of the Magi", written after Eliot\'s 1927 conversion to Anglicanism, marks a shift toward the possibility — though not the ease — of spiritual renewal.',
  majorConcernsHtml:
    'Modernity, urban alienation and spiritual paralysis; the fragmentation of coherent selfhood and belief in the early twentieth century; the use of dramatic monologue and free verse to enact psychological states formally rather than simply describe them; religious allusion and the difficulty (and eventual possibility) of spiritual redemption.',
  contextHtml:
    'Written across the collapse of pre-war certainties, the trauma of the First World War, and the broader modernist reaction against Victorian/Romantic literary convention. Eliot\'s poetry is frequently read as responding to a post-war "spiritual bankruptcy" — a loss of shared religious and moral frameworks — that leaves individuals (Prufrock, the speakers of Preludes and Rhapsody, the collective voice of The Hollow Men) unable to act decisively or find meaning. Eliot\'s own 1927 conversion to Anglicanism directly informs Journey of the Magi\'s shift toward the possibility of redemption through hardship.',
  significanceHtml:
    'As Module B\'s prescribed body of work, these poems are studied for how Eliot\'s formal innovations (fragmented syntax, the dramatic monologue, free verse, dense allusion) are inseparable from his ideas — the form does not just describe paralysis and disillusionment, it enacts them for the reader, which is exactly what a Module B close study asks students to demonstrate.',
  sections: [
    {
      id: 's-e-prufrock',
      order: 1,
      kind: 'poem',
      label: '"The Love Song of J. Alfred Prufrock" (1915)',
      summaryHtml:
        'A dramatic monologue narrated by Prufrock, a middle-aged man rehearsing, and endlessly deferring, a visit at which he might ask an "overwhelming question" (implicitly a romantic proposal). He circles the question through digression, self-doubt and minute anxieties about his appearance and social standing, before conceding at the poem\'s end that he lacks the courage to act, imagining himself instead as an aging, faintly ridiculous figure walking a beach, unable to summon even the mermaids\' song.',
      keyEvents: [
        'Prufrock invites the reader ("you and I") on a walk through a decaying urban landscape toward an unasked "overwhelming question"',
        'He rehearses and re-rehearses the moment of asking, paralysed by self-consciousness ("Do I dare / Disturb the universe?")',
        'He compares himself unfavourably to Hamlet, settling instead for the role of "the Fool"',
        'The poem ends with Prufrock imagining himself old, and concluding the mermaids "will not sing to me"',
      ],
      ideasIntroduced: [
        'Paralysis and the inability to act as the defining condition of the modern individual',
        'Fragmented, digressive form as an enactment (not just a description) of an anxious mind',
        'Trivial ritual (coffee spoons, toast and tea) standing in for lost meaning and purpose',
      ],
      charactersInFocus: ['prufrock-persona'],
      turningPointHtml:
        '"Do I dare / Disturb the universe?" is the poem\'s central, unanswered question — everything before and after it circles this single moment of failed nerve.',
      quoteIds: ['q-e-etherised', 'q-e-coffee-spoons', 'q-e-dare-disturb', 'q-e-prince-hamlet', 'q-e-mermaids'],
    },
    {
      id: 's-e-preludes',
      order: 2,
      kind: 'poem',
      label: '"Preludes" (1917)',
      summaryHtml:
        'Four short impressionistic sections depicting the grim, cyclical routine of urban life — a winter evening settling over "smell of steaks in passageways", a morning of "faint stale smells of beer", a woman waking to "a thousand sordid images", and a final meditation on "infinitely suffering" humanity trapped in mundane repetition.',
      keyEvents: [
        'Section I establishes a decaying, sensory urban evening',
        'Section II shifts to a monotonous morning of "masquerades" and repetition',
        'Section III turns to an unnamed woman\'s private, unglamorous waking ritual',
        'Section IV generalises to "some infinitely gentle / Infinitely suffering thing" beneath the city\'s surface',
      ],
      ideasIntroduced: [
        'Cyclical, repetitive time as a symbol of spiritual stagnation',
        'The city as a site of decay and lost community ("lonely cab-horse")',
        'A brief gesture of compassion ("infinitely suffering") undercutting the poem\'s otherwise detached, clinical tone',
      ],
      charactersInFocus: [],
      turningPointHtml: null,
      quoteIds: ['q-e-burnt-out-ends', 'q-e-thousand-sordid', 'q-e-infinitely-suffering'],
    },
    {
      id: 's-e-rhapsody',
      order: 3,
      kind: 'poem',
      label: '"Rhapsody on a Windy Night" (1917)',
      summaryHtml:
        'A speaker walks through a city at night, each street lamp (personified, speaking directly) forcing a fragmented "memory" of disturbing images — a twisted woman, a rusted spring, a cat devouring rancid butter, the moon\'s "lost" memory — culminating at "four o\'clock" with an instruction to prepare for sleep and "life", closing on the line "the last twist of the knife".',
      keyEvents: [
        'The speaker moves through the city as successive street lamps mark the hours (twelve, half-past one, half-past two, half-past three, four o\'clock)',
        'Each lamp forces up a disturbing, disconnected memory-image',
        'The moon is personified as having "lost her memory"',
        'The poem ends with an ambiguous instruction to sleep and "prepare for life"',
      ],
      ideasIntroduced: [
        'Memory as fragmented and involuntary rather than coherent or comforting',
        'Personification of inanimate urban objects (lamps, the moon) as a device for detached, unsettling narration',
        'The structuring device of clock-time marking a descent rather than a progression',
      ],
      charactersInFocus: [],
      turningPointHtml: null,
      quoteIds: ['q-e-lunar-synthesis', 'q-e-street-lamp-said', 'q-e-last-twist'],
    },
    {
      id: 's-e-hollow-men',
      order: 4,
      kind: 'poem',
      label: '"The Hollow Men" (1925)',
      summaryHtml:
        'A collective, depersonalised speaker ("we") describes itself as "hollow", "stuffed", lacking the moral substance to be either genuinely good or genuinely evil. The poem moves through a series of "kingdoms" (death\'s dream kingdom, death\'s other kingdom, twilight kingdom) before ending with the famous, deflating close: the world does not end in apocalyptic violence but in quiet anticlimax.',
      keyEvents: [
        'The collective "we" identifies itself as "hollow men… stuffed men"',
        'Section II-IV move through successive "kingdom" images associated with death and moral emptiness',
        'The "Shadow" motif repeatedly falls between intention and action ("Between the idea / And the reality… Falls the Shadow")',
        'The poem ends: "This is the way the world ends… Not with a bang but a whimper"',
      ],
      ideasIntroduced: [
        'Collective, rather than individual, spiritual paralysis — a post-war "malaise" rather than one man\'s neurosis',
        'The impossibility of decisive moral action (neither virtue nor vice, only emptiness)',
        'Intertextual allusion (Conrad\'s Heart of Darkness, Guy Fawkes Day, Dante) layering historical and literary meaning onto contemporary disillusionment',
      ],
      charactersInFocus: ['hollow-men-collective'],
      turningPointHtml:
        'The final "not with a bang but a whimper" line is the poem\'s (and arguably the module\'s) most quoted moment — the deliberate anticlimax is itself the point.',
      quoteIds: ['q-e-hollow-stuffed', 'q-e-mistah-kurtz', 'q-e-the-shadow', 'q-e-bang-whimper'],
    },
    {
      id: 's-e-magi',
      order: 5,
      kind: 'poem',
      label: '"Journey of the Magi" (1927)',
      summaryHtml:
        'A retrospective dramatic monologue narrated by one of the biblical Magi, recalling the arduous journey to witness Christ\'s birth. The Magus recalls physical hardship, temptation to turn back, and a brief vision of renewal at a "temperate valley" — before concluding, on returning to his own kingdom, that he is "no longer at ease here" among "an alien people clutching their gods", and would welcome his own death.',
      keyEvents: [
        'The Magus recalls the hardship of the journey ("A cold coming we had of it")',
        'Temptation to abandon the journey for comfort ("the summer palaces… the silken girls")',
        'A brief vision of renewal at a temperate valley with a water-mill and three trees',
        'The Magus returns changed, "no longer at ease" in his old life, and wishes for death',
      ],
      ideasIntroduced: [
        'Spiritual rebirth as inseparable from suffering and loss, not a simple relief',
        'A shift from the intimate, confessional "I" of Prufrock/Hollow Men to a detached, retrospective speaker',
        'Hope, but qualified hope — redemption exists, but it estranges the Magus from his old life permanently',
      ],
      charactersInFocus: ['magus-persona'],
      turningPointHtml:
        'The Magus\'s closing admission that he "should be glad of another death" reframes the poem\'s hope as costly rather than comfortable — a deliberate complication of any simple redemptive reading.',
      quoteIds: ['q-e-cold-coming', 'q-e-temperate-valley', 'q-e-no-longer-at-ease'],
    },
  ],
  characters: [
    {
      id: 'prufrock-persona',
      name: 'The Prufrock persona',
      roleHtml:
        'The speaker of "The Love Song of J. Alfred Prufrock" — an anxious, self-conscious middle-aged man, often read as a persona standing between Eliot and the reader rather than a strictly autobiographical voice.',
      relationshipsHtml: 'Addresses an unnamed "you" throughout, inviting the reader into his own paralysed interior monologue.',
      developmentHtml: 'Never changes or acts — the poem\'s structure (circling, digressive, endlessly deferred) is itself evidence that Prufrock cannot move past his own hesitation.',
      associatedThemeIds: ['th-e-paralysis'],
      quoteIds: ['q-e-etherised', 'q-e-coffee-spoons', 'q-e-dare-disturb', 'q-e-prince-hamlet', 'q-e-mermaids'],
    },
    {
      id: 'hollow-men-collective',
      name: 'The hollow men (collective voice)',
      roleHtml: 'A depersonalised "we" — not an individual character but a post-war collective, explicitly stripped of individual identity.',
      relationshipsHtml: 'Speaks of itself only in the plural; other figures (Mr Kurtz, "death\'s other Kingdom") are referenced but never directly addressed.',
      developmentHtml: 'Static and unchanging by design — the poem\'s point is precisely that this collective cannot develop or act.',
      associatedThemeIds: ['th-e-paralysis', 'th-e-modernity'],
      quoteIds: ['q-e-hollow-stuffed', 'q-e-mistah-kurtz', 'q-e-the-shadow', 'q-e-bang-whimper'],
    },
    {
      id: 'magus-persona',
      name: 'The Magus',
      roleHtml: 'The retrospective narrator of "Journey of the Magi" — one of the biblical Magi, recalling his journey to witness Christ\'s birth from a position of later, uneasy hindsight.',
      relationshipsHtml: 'Speaks collectively of "we" (the Magi) during the journey, but reflects individually on its cost at the poem\'s end.',
      developmentHtml: 'The only speaker across the five poems who is explicitly transformed by the events of his own poem — but Eliot deliberately makes that transformation costly, not comfortable.',
      associatedThemeIds: ['th-e-redemption'],
      quoteIds: ['q-e-cold-coming', 'q-e-temperate-valley', 'q-e-no-longer-at-ease'],
    },
  ],
  themes: [
    {
      id: 'th-e-paralysis',
      name: 'Paralysis and the inability to act',
      explanationHtml: 'Across Prufrock and The Hollow Men especially, Eliot\'s speakers are defined by their inability to move from intention to action — a condition the poems\' fragmented, circling form enacts rather than simply describes.',
      developmentHtml: 'Introduced through Prufrock\'s endlessly deferred "overwhelming question", intensified and made collective in The Hollow Men\'s "Shadow" that falls between "the idea / And the reality".',
      keySectionIds: ['s-e-prufrock', 's-e-hollow-men'],
      associatedCharacterIds: ['prufrock-persona', 'hollow-men-collective'],
      quoteIds: ['q-e-dare-disturb', 'q-e-the-shadow'],
      techniqueIds: ['t-e-fragmented-syntax', 't-e-dramatic-monologue'],
      possibleArguments: [
        'Eliot uses fragmented, digressive syntax to formally enact paralysis rather than simply narrate it',
        'The shift from Prufrock\'s individual paralysis to The Hollow Men\'s collective paralysis reflects a broadening, post-war diagnosis of the same condition',
      ],
    },
    {
      id: 'th-e-modernity',
      name: 'Modernity, urban decay and spiritual emptiness',
      explanationHtml: 'Eliot repeatedly figures modern urban life through images of decay, repetition and triviality (coffee spoons, "sawdust restaurants", "smell of steaks in passageways"), suggesting that modernity has replaced meaningful ritual with empty routine.',
      developmentHtml: 'Established through Prufrock\'s trivial social rituals, deepened through Preludes\' cyclical urban squalor and Rhapsody\'s disturbing fragmented memories, and generalised to a whole post-war collective in The Hollow Men.',
      keySectionIds: ['s-e-prufrock', 's-e-preludes', 's-e-rhapsody', 's-e-hollow-men'],
      associatedCharacterIds: ['hollow-men-collective'],
      quoteIds: ['q-e-coffee-spoons', 'q-e-burnt-out-ends', 'q-e-lunar-synthesis'],
      techniqueIds: ['t-e-imagery', 't-e-personification', 't-e-symbolism'],
      possibleArguments: [
        'Eliot\'s repeated trivial, domestic imagery (coffee spoons, toast and tea) critiques a modernity that has substituted ritual for meaning',
        'The personified street lamps and moon in Rhapsody suggest even the inanimate urban world has been drained of genuine vitality',
      ],
    },
    {
      id: 'th-e-redemption',
      name: 'Religious allusion and the possibility of redemption',
      explanationHtml: 'Eliot\'s poetic canon moves from the spiritual emptiness of Prufrock and The Hollow Men toward the qualified hope of Journey of the Magi, written after his 1927 conversion — but redemption, when it appears, is costly and estranging rather than comfortable.',
      developmentHtml: 'Anticipated through religious allusion even in the earlier, more despairing poems (Prufrock\'s allusion to John the Baptist, The Hollow Men\'s "kingdom" imagery and Dantean eyes), and resolved — ambivalently — in Journey of the Magi.',
      keySectionIds: ['s-e-magi'],
      associatedCharacterIds: ['magus-persona'],
      quoteIds: ['q-e-cold-coming', 'q-e-no-longer-at-ease'],
      techniqueIds: ['t-e-allusion', 't-e-imagery'],
      possibleArguments: [
        'Eliot\'s poetic canon traces a genuine spiritual arc from disillusionment to hope, not just a series of unrelated moods',
        'Journey of the Magi complicates any straightforwardly hopeful reading — the Magus\'s redemption costs him his old life entirely, and he ends the poem wishing for death',
      ],
    },
  ],
  quotes: [
    {
      id: 'q-e-etherised',
      textHtml: 'Let us go then, you and I, / When the evening is spread out against the sky / Like a patient etherised upon a table',
      speaker: 'The Prufrock persona',
      location: '"The Love Song of J. Alfred Prufrock", opening lines',
      sectionId: 's-e-prufrock',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-simile', 't-e-dramatic-monologue'],
      characterIds: ['prufrock-persona'],
      contextHtml: 'The poem\'s opening image, inviting the reader ("you and I") on a walk through the city.',
      revealsHtml: 'The startling, clinical simile ("etherised upon a table") immediately signals a world drained of romantic possibility — even the evening sky is rendered as something inert and medically anaesthetised, not beautiful.',
      authorialPurposeHtml: 'Establishes the poem\'s anti-Romantic register from its very first lines, rejecting conventional poetic imagery of evening in favour of something jarring and modern.',
      argumentHtml: 'A strong opening quote for any essay on Eliot\'s modernist rejection of Romantic convention.',
    },
    {
      id: 'q-e-coffee-spoons',
      textHtml: 'I have measured out my life with coffee spoons',
      speaker: 'The Prufrock persona',
      location: '"The Love Song of J. Alfred Prufrock"',
      sectionId: 's-e-prufrock',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-symbolism'],
      characterIds: ['prufrock-persona'],
      contextHtml: 'Prufrock reflects on the smallness and repetitiveness of his life.',
      revealsHtml: 'The coffee spoon becomes a symbol of trivial, endlessly repeated social ritual standing in for a life never fully lived — measuring existence in teaspoons rather than meaningful achievement.',
      authorialPurposeHtml: 'One of Eliot\'s most famous images for how modernity substitutes empty ritual for genuine purpose or meaning.',
      argumentHtml: 'Essential, widely-recognisable evidence for the modernity/triviality theme — almost always worth including.',
    },
    {
      id: 'q-e-dare-disturb',
      textHtml: 'Do I dare / Disturb the universe?',
      speaker: 'The Prufrock persona',
      location: '"The Love Song of J. Alfred Prufrock"',
      sectionId: 's-e-prufrock',
      themeIds: ['th-e-paralysis'],
      techniqueIds: ['t-e-fragmented-syntax', 't-e-rhetorical-question'],
      characterIds: ['prufrock-persona'],
      contextHtml: 'Prufrock questions whether he has the courage to ask his "overwhelming question".',
      revealsHtml: 'The line break after "dare" enacts the very hesitation it describes — the question is left suspended, formally performing Prufrock\'s inability to commit even to a single unbroken thought.',
      authorialPurposeHtml: 'The poem\'s central rhetorical question, deliberately never definitively answered, showing form and content working together to convey paralysis.',
      argumentHtml: 'The single most important Prufrock quote for any essay on paralysis or the relationship between form and meaning.',
    },
    {
      id: 'q-e-prince-hamlet',
      textHtml: 'I am not Prince Hamlet, nor was meant to be… At times, the Fool',
      speaker: 'The Prufrock persona',
      location: '"The Love Song of J. Alfred Prufrock"',
      sectionId: 's-e-prufrock',
      themeIds: ['th-e-paralysis'],
      techniqueIds: ['t-e-allusion'],
      characterIds: ['prufrock-persona'],
      contextHtml: 'Prufrock compares himself to Shakespeare\'s Hamlet and finds himself lacking.',
      revealsHtml: 'By explicitly rejecting the role of tragic hero in favour of "the Fool", Prufrock reveals he sees himself as comic relief in his own life rather than someone capable of decisive, meaningful action.',
      authorialPurposeHtml: 'The Shakespearean allusion lets Eliot characterise Prufrock through negation — defining him by the heroic role he explicitly knows he cannot fill.',
      argumentHtml: 'Useful for essays on self-characterisation through literary allusion specifically.',
    },
    {
      id: 'q-e-mermaids',
      textHtml: 'I have heard the mermaids singing, each to each. / I do not think that they will sing to me.',
      speaker: 'The Prufrock persona',
      location: '"The Love Song of J. Alfred Prufrock", closing lines',
      sectionId: 's-e-prufrock',
      themeIds: ['th-e-paralysis'],
      techniqueIds: ['t-e-symbolism'],
      characterIds: ['prufrock-persona'],
      contextHtml: 'Near the poem\'s end, Prufrock imagines mermaids — a symbol of romantic, mythic possibility — singing to each other but not to him.',
      revealsHtml: 'The mermaids\' song, one of the poem\'s only images of genuine beauty and possibility, is explicitly withheld from Prufrock — his own final judgement on his exclusion from meaningful romantic or spiritual experience.',
      authorialPurposeHtml: 'Closes the poem on quiet, resigned exclusion rather than dramatic tragedy, reinforcing that Prufrock\'s failure is one of nerve, not circumstance.',
      argumentHtml: 'A strong closing-line quote for essays discussing the poem\'s resolution (or lack of one).',
    },
    {
      id: 'q-e-burnt-out-ends',
      textHtml: 'The winter evening settles down / With smell of steaks in passageways… The burnt-out ends of smoky days.',
      speaker: 'Narrator',
      location: '"Preludes", Section I',
      sectionId: 's-e-preludes',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-imagery'],
      characterIds: [],
      contextHtml: 'The opening of "Preludes", establishing a decaying urban winter evening.',
      revealsHtml: 'The unglamorous sensory detail ("smell of steaks in passageways") and the metaphor of days as cigarette-like "burnt-out ends" establish urban modernity as something consumed and discarded rather than lived fully.',
      authorialPurposeHtml: 'Sets the poem\'s clinical, unsentimental tone toward the modern city from its opening image.',
      argumentHtml: 'Good opening evidence for essays on urban decay imagery across the poems.',
    },
    {
      id: 'q-e-thousand-sordid',
      textHtml: 'The thousand sordid images / Of which your soul was constituted',
      speaker: 'Narrator (second person)',
      location: '"Preludes", Section III',
      sectionId: 's-e-preludes',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-second-person'],
      characterIds: [],
      contextHtml: 'A description of a woman waking, her private thoughts characterised as accumulated "sordid images".',
      revealsHtml: 'The second-person address implicates the reader directly in this unflattering, intimate portrait, while "constituted" suggests identity itself has been built from nothing but these shabby fragments.',
      authorialPurposeHtml: 'Demonstrates Eliot\'s use of second-person address to collapse distance between reader and subject, a technique that recurs across the sequence.',
      argumentHtml: 'Useful for essays specifically on Eliot\'s use of narrative perspective/address.',
    },
    {
      id: 'q-e-infinitely-suffering',
      textHtml: 'The notion of some infinitely gentle / Infinitely suffering thing',
      speaker: 'Narrator',
      location: '"Preludes", Section IV',
      sectionId: 's-e-preludes',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-repetition'],
      characterIds: [],
      contextHtml: 'The poem\'s final section briefly generalises from specific urban squalor to a compassionate meditation on suffering.',
      revealsHtml: 'The anaphoric repetition of "infinitely" is the poem\'s single moment of genuine tenderness, briefly interrupting its otherwise detached, clinical cataloguing of urban decay.',
      authorialPurposeHtml: 'Complicates a purely cynical reading of the sequence — Eliot allows a flicker of compassion before the poem\'s final, more dismissive closing image.',
      argumentHtml: 'Important complicating evidence against a reading of Eliot as purely contemptuous of modern humanity.',
    },
    {
      id: 'q-e-lunar-synthesis',
      textHtml: 'Held in a lunar synthesis, / Whispering lunar incantations / Dissolve the floors of memory',
      speaker: 'Narrator',
      location: '"Rhapsody on a Windy Night", opening',
      sectionId: 's-e-rhapsody',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-imagery'],
      characterIds: [],
      contextHtml: 'The poem\'s opening, as the speaker begins a nighttime walk through the city.',
      revealsHtml: 'Eliot subverts the traditional Romantic association of moonlight with guidance and mysticism, instead figuring it as a "sinister" incantation that dissolves coherent memory rather than illuminating anything.',
      authorialPurposeHtml: 'Recasts a conventionally beautiful Romantic image (moonlight) as disorienting and hypnotic, reinforcing the poem\'s unsettling, fragmented mode.',
      argumentHtml: 'Strong evidence for essays on Eliot\'s subversion of Romantic convention specifically.',
    },
    {
      id: 'q-e-street-lamp-said',
      textHtml: 'The street lamp sputtered, / The street lamp muttered, / The street lamp said, "Regard that woman…"',
      speaker: 'The street lamp (personified)',
      location: '"Rhapsody on a Windy Night"',
      sectionId: 's-e-rhapsody',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-personification'],
      characterIds: [],
      contextHtml: 'The poem\'s structuring device — successive personified street lamps direct the speaker\'s attention to disturbing images.',
      revealsHtml: 'Personifying an inanimate object as the poem\'s controlling voice removes human agency from the act of noticing and judging — even observation itself has become mechanical and detached in Eliot\'s modern city.',
      authorialPurposeHtml: 'A formally inventive way to structure the poem\'s fragmented images around clock-time while keeping the human speaker passive throughout.',
      argumentHtml: 'Central evidence for any essay focused on personification as a technique across the poems.',
    },
    {
      id: 'q-e-last-twist',
      textHtml: 'Put your shoes at the door, sleep, prepare for life. / The last twist of the knife',
      speaker: 'The street lamp (personified)',
      location: '"Rhapsody on a Windy Night", closing lines',
      sectionId: 's-e-rhapsody',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-metaphor'],
      characterIds: [],
      contextHtml: 'The poem\'s final instruction, as the speaker reaches home at four o\'clock.',
      revealsHtml: 'The abrupt, violent metaphor of a "twist of the knife" attached to the banal instruction to "prepare for life" suggests ordinary daily existence itself is a kind of ongoing wound, not a relief from the night\'s disturbing visions.',
      authorialPurposeHtml: 'Ends the poem on deliberate anticlimax and unease rather than resolution, consistent with the sequence\'s refusal of comfort.',
      argumentHtml: 'A sharp closing quote for essays on Eliot\'s refusal of neat resolution.',
    },
    {
      id: 'q-e-hollow-stuffed',
      textHtml: 'We are the hollow men / We are the stuffed men / Leaning together / Headpiece filled with straw.',
      speaker: 'The hollow men (collective)',
      location: '"The Hollow Men", Section I',
      sectionId: 's-e-hollow-men',
      themeIds: ['th-e-paralysis', 'th-e-modernity'],
      techniqueIds: ['t-e-repetition', 't-e-imagery'],
      characterIds: ['hollow-men-collective'],
      contextHtml: 'The poem\'s opening, establishing its collective, depersonalised speaker.',
      revealsHtml: 'The droning, repetitive syntax ("We are… We are…") enacts the very emptiness it describes, while "headpiece filled with straw" (an allusion to the scarecrow) strips the collective of any interior substance at all.',
      authorialPurposeHtml: 'Establishes the poem\'s collective rather than individual voice from its first lines, broadening Prufrock\'s individual paralysis into a post-war condition.',
      argumentHtml: 'The single most important opening quote for The Hollow Men — almost always worth including.',
    },
    {
      id: 'q-e-mistah-kurtz',
      textHtml: 'Mistah Kurtz - he dead',
      speaker: 'Epigraph (attributed within the poem to a servant in Heart of Darkness)',
      location: '"The Hollow Men", epigraph',
      sectionId: 's-e-hollow-men',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-allusion'],
      characterIds: [],
      contextHtml: 'The poem\'s epigraph, quoting a line from Joseph Conrad\'s Heart of Darkness.',
      revealsHtml: 'By opening with the death of Conrad\'s Kurtz — a man of decisive, if monstrous, action and will — Eliot immediately establishes decisive action itself as a thing of the past, unavailable to his own hollow, paralysed speakers.',
      authorialPurposeHtml: 'A dense intertextual allusion that lets Eliot invoke an entire earlier work\'s meditation on civilisation and moral darkness in a single line.',
      argumentHtml: 'Essential for any essay discussing Eliot\'s use of allusion and intertextuality specifically.',
    },
    {
      id: 'q-e-the-shadow',
      textHtml: 'Between the idea / And the reality… Falls the Shadow',
      speaker: 'The hollow men (collective)',
      location: '"The Hollow Men", Section V',
      sectionId: 's-e-hollow-men',
      themeIds: ['th-e-paralysis'],
      techniqueIds: ['t-e-anaphora', 't-e-symbolism'],
      characterIds: ['hollow-men-collective'],
      contextHtml: 'The poem\'s final section, repeated across several parallel pairings (idea/reality, motion/act, conception/creation).',
      revealsHtml: 'The capitalised "Shadow" becomes a symbol for the gap between intention and action itself — repeated across four parallel binaries, it insists that this gap is total and unbridgeable, not occasional.',
      authorialPurposeHtml: 'The poem\'s clearest, most abstract statement of its central theme, delivered through structural repetition rather than a single explanatory line.',
      argumentHtml: 'The key quote for any essay specifically on the paralysis theme across Eliot\'s canon.',
    },
    {
      id: 'q-e-bang-whimper',
      textHtml: 'This is the way the world ends… Not with a bang but a whimper.',
      speaker: 'The hollow men (collective)',
      location: '"The Hollow Men", closing lines',
      sectionId: 's-e-hollow-men',
      themeIds: ['th-e-modernity'],
      techniqueIds: ['t-e-anticlimax'],
      characterIds: ['hollow-men-collective'],
      contextHtml: 'The poem\'s final, most famous lines.',
      revealsHtml: 'The deliberate anticlimax — expecting apocalyptic violence ("a bang") and receiving only quiet failure ("a whimper") — is itself Eliot\'s argument: modernity\'s real danger is not dramatic collapse but slow, unremarkable surrender of meaning.',
      authorialPurposeHtml: 'One of the most quoted closing lines in modernist poetry, deliberately refusing the dramatic resolution a reader might expect.',
      argumentHtml: 'Essential closing evidence for almost any essay on this poem — but should be paired with analysis of WHY the anticlimax matters, not just quoted for recognition.',
    },
    {
      id: 'q-e-cold-coming',
      textHtml: 'A cold coming we had of it, / Just the worst time of the year / For a journey, and such a long journey',
      speaker: 'The Magus',
      location: '"Journey of the Magi", opening lines',
      sectionId: 's-e-magi',
      themeIds: ['th-e-redemption'],
      techniqueIds: ['t-e-allusion', 't-e-dramatic-monologue'],
      characterIds: ['magus-persona'],
      contextHtml: 'The poem\'s opening, paraphrasing a real 1622 Nativity sermon by the Anglican bishop Lancelot Andrewes.',
      revealsHtml: 'By opening with an allusion to a real historical sermon, Eliot immediately signals the shift to a religious, retrospective register distinct from the earlier poems\' anxious, present-tense interiority.',
      authorialPurposeHtml: 'Establishes the poem\'s detached, retrospective dramatic-monologue form from its first line, distinguishing this poem\'s mode from Prufrock\'s and The Hollow Men\'s intimate confessional voice.',
      argumentHtml: 'Useful for essays on the shift in form/voice across Eliot\'s canon specifically.',
    },
    {
      id: 'q-e-temperate-valley',
      textHtml: 'Then at dawn we came down to a temperate valley… with a running stream and a water-mill beating the darkness',
      speaker: 'The Magus',
      location: '"Journey of the Magi"',
      sectionId: 's-e-magi',
      themeIds: ['th-e-redemption'],
      techniqueIds: ['t-e-allusion', 't-e-imagery'],
      characterIds: ['magus-persona'],
      contextHtml: 'A brief moment of relief partway through the arduous journey.',
      revealsHtml: 'The running stream and water-mill evoke baptismal imagery (the Jordan river, Christian ritual rebirth), offering the Magus — and the reader — a brief vision of spiritual renewal amid an otherwise gruelling journey.',
      authorialPurposeHtml: 'Uses concrete, sensory imagery with religious allusion built in, rather than stating the idea of renewal directly.',
      argumentHtml: 'Key evidence for essays on the poem\'s qualified hope and its religious imagery specifically.',
    },
    {
      id: 'q-e-no-longer-at-ease',
      textHtml: "We returned to our places, these Kingdoms, / But no longer at ease here, in the old dispensation, / With an alien people clutching their gods.",
      speaker: 'The Magus',
      location: '"Journey of the Magi", closing lines',
      sectionId: 's-e-magi',
      themeIds: ['th-e-redemption'],
      techniqueIds: ['t-e-imagery'],
      characterIds: ['magus-persona'],
      contextHtml: 'The Magus reflects on his life after witnessing the Nativity.',
      revealsHtml: 'The Magus\'s spiritual transformation has permanently estranged him from his old life — "alien" recasts his own former home and people as foreign, revealing redemption\'s cost rather than its comfort.',
      authorialPurposeHtml: 'Complicates any simple "hope wins" reading of the poem — Eliot insists that genuine spiritual change is estranging and costly, not simply comforting.',
      argumentHtml: 'The essential quote for any argument that Journey of the Magi offers qualified, not simple, hope.',
    },
  ],
  techniques: [
    {
      id: 't-e-dramatic-monologue',
      name: 'Dramatic monologue',
      category: 'narrative-voice',
      definitionHtml: 'A poem spoken entirely in the voice of a single persona (not necessarily the poet), often addressing an implied listener.',
      effectHtml: 'Creates psychological intimacy with a character\'s interior state while maintaining ironic distance between poet and speaker.',
      whyAuthorsUseItHtml: 'Eliot uses the form across most of these poems to place the reader directly inside a mind\'s anxiety or reflection, rather than describing that mind from outside.',
      exampleQuoteId: 'q-e-etherised',
      genericExampleHtml: null,
      analyticalLanguage: ['places the reader inside the persona\'s consciousness', 'creates an intimate yet ironic distance between poet and speaker', 'enacts rather than describes'],
      howToRecogniseHtml: 'A poem entirely in one voice, often with an implied "you" being addressed, and no external narrator commenting on the speaker.',
      commonMistakeHtml: 'Assuming the speaker is simply Eliot himself — the "confessional I" is deliberately never quite Eliot and never quite not him.',
      confusedWithIds: [],
    },
    {
      id: 't-e-fragmented-syntax',
      name: 'Fragmented syntax and meter',
      category: 'structure-and-form',
      definitionHtml: 'Broken, interrupted sentence structure and irregular metrical rhythm rather than smooth, conventional verse.',
      effectHtml: 'Mimics an anxious, hesitant or distracted thought process rather than a settled, confident one.',
      whyAuthorsUseItHtml: 'Eliot uses fragmentation formally to enact Prufrock\'s (and later the hollow men\'s) psychological paralysis, so the reader experiences hesitation rather than being told about it.',
      exampleQuoteId: 'q-e-dare-disturb',
      genericExampleHtml: null,
      analyticalLanguage: ['formally enacts the hesitation it describes', 'mirrors the paralysed rhythm of', 'interrupts the expected flow of'],
      howToRecogniseHtml: 'Short, broken lines; sentences that trail off or restart; irregular rhythm rather than a consistent metrical pattern.',
      commonMistakeHtml: 'Describing fragmentation only as "showing confusion" without connecting it to the poem\'s specific psychological or thematic concern.',
      confusedWithIds: [],
    },
    {
      id: 't-e-simile',
      name: 'Simile',
      category: 'figurative-language',
      definitionHtml: 'A direct comparison using "like" or "as" — here, the evening compared to an anaesthetised patient.',
      effectHtml: 'Creates a jarring, unexpected image that immediately signals a rejection of conventional poetic beauty.',
      whyAuthorsUseItHtml: 'Eliot deliberately chooses clinical, anti-Romantic similes to signal modernist rejection of Victorian/Romantic poetic convention from the poem\'s opening lines.',
      exampleQuoteId: 'q-e-etherised',
      genericExampleHtml: null,
      analyticalLanguage: ['jars against conventional expectations of', 'signals a rejection of Romantic convention through', 'renders [X] clinically rather than beautifully'],
      howToRecogniseHtml: 'A comparison using "like" or "as" that deliberately undercuts or subverts what would normally be a beautiful or comforting image.',
      commonMistakeHtml: 'Identifying the simile without explaining why the specific comparison (medical/clinical) is jarring against the reader\'s expectations.',
      confusedWithIds: [],
    },
    {
      id: 't-e-symbolism',
      name: 'Symbolism',
      category: 'symbolism-and-motif',
      definitionHtml: 'Concrete objects standing in for abstract ideas — coffee spoons for wasted time, mermaids for unattainable beauty.',
      effectHtml: 'Compresses a large, abstract idea into a small, memorable, concrete image.',
      whyAuthorsUseItHtml: 'Eliot favours small, domestic or mundane symbols over grand ones, reinforcing his theme that modernity has shrunk meaning down to trivial scale.',
      exampleQuoteId: 'q-e-coffee-spoons',
      genericExampleHtml: null,
      analyticalLanguage: ['compresses [abstract idea] into the concrete image of', 'stands in for', 'reduces [X] to trivial scale through'],
      howToRecogniseHtml: 'A specific, recurring or otherwise foregrounded object clearly tied to one abstract idea rather than used purely descriptively.',
      commonMistakeHtml: 'Treating every concrete noun as symbolic — reserve this for objects Eliot foregrounds or returns to deliberately.',
      confusedWithIds: [],
    },
    {
      id: 't-e-allusion',
      name: 'Allusion (literary, biblical, historical)',
      category: 'language-and-diction',
      definitionHtml: 'A reference to another text, figure or event outside the poem — Hamlet, John the Baptist, Heart of Darkness, a 1622 Nativity sermon.',
      effectHtml: 'Imports an entire external context and its associations into a single line, without needing to state them directly.',
      whyAuthorsUseItHtml: 'Eliot is famous for dense, compressed allusion — a hallmark of modernist poetry\'s assumption of a highly literate reader able to recognise and unpack these references.',
      exampleQuoteId: 'q-e-mistah-kurtz',
      genericExampleHtml: null,
      analyticalLanguage: ['imports the associations of [source text] into', 'invokes [external context] to compress meaning', 'layers historical/literary meaning onto'],
      howToRecogniseHtml: 'A named figure, quoted phrase or referenced event the reader is assumed to recognise from outside the poem itself.',
      commonMistakeHtml: 'Naming the allusion\'s source without explaining what specific meaning or association it imports into the poem.',
      confusedWithIds: [],
    },
    {
      id: 't-e-personification',
      name: 'Personification',
      category: 'figurative-language',
      definitionHtml: 'Giving human qualities (speech, sputtering, muttering) to inanimate objects — street lamps and the moon in Rhapsody.',
      effectHtml: 'Removes human agency from observation and judgement, suggesting even perception itself has become mechanical.',
      whyAuthorsUseItHtml: 'Eliot personifies the urban environment specifically to make the speaker passive — the city itself directs attention, rather than a human consciousness choosing what to notice.',
      exampleQuoteId: 'q-e-street-lamp-said',
      genericExampleHtml: null,
      analyticalLanguage: ['removes human agency from', 'renders [the city] as an active, controlling presence', 'displaces observation from the human speaker onto'],
      howToRecogniseHtml: 'An inanimate object given verbs or qualities normally reserved for living, especially speaking, beings.',
      commonMistakeHtml: 'Identifying personification without connecting it to the poem\'s broader concern with passivity/paralysis.',
      confusedWithIds: [],
    },
    {
      id: 't-e-anaphora',
      name: 'Anaphora',
      category: 'sound',
      definitionHtml: 'Repetition of a word or phrase at the start of successive lines or clauses — "We are… We are…", "Between… Between…".',
      effectHtml: 'Builds an accumulating, almost ritualistic rhythm, often reinforcing the very stasis or repetition being described.',
      whyAuthorsUseItHtml: 'Eliot uses anaphora to formally enact repetition and stasis (The Hollow Men\'s emptiness, the Shadow\'s inescapability) rather than just naming these ideas.',
      exampleQuoteId: 'q-e-the-shadow',
      genericExampleHtml: null,
      analyticalLanguage: ['formally enacts the repetition/stasis it describes', 'builds a ritualistic, incantatory rhythm around', 'insists on the totality of [X] through repeated structure'],
      howToRecogniseHtml: 'The same word or phrase repeated at the start of consecutive lines or clauses.',
      commonMistakeHtml: 'Simply noting "repetition" without the more precise term (anaphora) or its structural, accumulating effect.',
      confusedWithIds: [],
    },
    {
      id: 't-e-anticlimax',
      name: 'Anticlimax',
      category: 'structure-and-form',
      definitionHtml: 'A deliberate deflation of expectation — building toward something dramatic, then delivering something quiet or unremarkable instead.',
      effectHtml: 'Subverts the reader\'s expectation in a way that makes the quiet outcome feel more unsettling than a dramatic one would have.',
      whyAuthorsUseItHtml: 'Eliot\'s "not with a bang but a whimper" is a deliberate refusal of the apocalyptic climax the poem\'s religious/mythic imagery has been building toward, making the point that modernity\'s real danger is unremarkable, not dramatic.',
      exampleQuoteId: 'q-e-bang-whimper',
      genericExampleHtml: null,
      analyticalLanguage: ['deliberately deflates the expectation of', 'refuses the dramatic resolution the reader anticipates', 'makes the quiet outcome more unsettling than'],
      howToRecogniseHtml: 'Language or imagery that builds toward a dramatic or significant event, followed by a deliberately understated or quiet resolution.',
      commonMistakeHtml: 'Treating the line as simply "famous" without explaining why the specific deflation (violence to quietness) is the poem\'s point.',
      confusedWithIds: [],
    },
  ],
  shortAnswerQuestions: [
    {
      id: 'sa-e-1',
      qtype: 'identify',
      prompt: 'Identify the technique Eliot uses in "Do I dare / Disturb the universe?" and explain its effect.',
      marks: 2,
      stimulusHtml: null,
      modelAnswerHtml: 'Eliot uses fragmented syntax, breaking the sentence across the line break after "dare". This formally enacts Prufrock\'s hesitation — the reader experiences the same suspended uncertainty Prufrock feels, rather than simply being told he is uncertain.',
      markingGuidanceHtml: 'Award 1 mark for correctly identifying fragmented syntax/line break; award a second mark for explaining the formal enactment of hesitation, not just a general "shows uncertainty" statement.',
      keyPoints: ['Identifies the line-break fragmentation specifically', 'Explains the formal (not just thematic) effect'],
      relevantQuoteIds: ['q-e-dare-disturb'],
      strongerResponseHtml: 'A stronger response would connect this to the poem\'s broader pattern of fragmented, digressive syntax across every stanza, not just this one line.',
    },
    {
      id: 'sa-e-2',
      qtype: 'explain',
      prompt: 'Explain how Eliot uses personification in "Rhapsody on a Windy Night" to shape the reader\'s experience of the poem.',
      marks: 3,
      stimulusHtml: null,
      modelAnswerHtml: 'The street lamps are personified as speaking, directing the speaker\'s (and reader\'s) attention to a series of disturbing images ("The street lamp said, \'Regard that woman…\'"). This removes human agency from the act of noticing and judging, suggesting that even perception has become passive and mechanical in Eliot\'s vision of the modern city.',
      markingGuidanceHtml: 'Look for reference to the personified lamps specifically, and an explanation of how this shifts agency away from the human speaker, not just a general "makes it more vivid" statement.',
      keyPoints: ['References the personified street lamps', 'Explains the shift of agency away from the human speaker', 'Connects to the poem\'s broader concern with passivity'],
      relevantQuoteIds: ['q-e-street-lamp-said'],
      strongerResponseHtml: 'A stronger response would also note the personified moon later in the poem as a second instance of the same device, building a fuller pattern.',
    },
    {
      id: 'sa-e-3',
      qtype: 'analyse',
      prompt: 'Analyse how the anticlimactic ending of "The Hollow Men" contributes to its critique of modernity.',
      marks: 4,
      stimulusHtml: null,
      modelAnswerHtml: 'The poem builds toward an apocalyptic expectation through its religious and mythic imagery ("kingdoms", "death\'s twilight kingdom"), before deflating that expectation entirely: "This is the way the world ends… Not with a bang but a whimper." This anticlimax is the poem\'s central argument — Eliot suggests that modernity\'s true danger is not dramatic, violent collapse but a slow, unremarkable surrender of meaning and purpose, which is arguably more unsettling precisely because it offers no clear moment of crisis to resist.',
      markingGuidanceHtml: 'Award marks for identifying the anticlimax technique specifically, linking it to the poem\'s broader religious/apocalyptic imagery it deflates, and analysing why the quiet ending is more unsettling than a dramatic one, not just noting that it is famous.',
      keyPoints: ['Identifies the deliberate anticlimax/deflation', 'Links to the poem\'s earlier apocalyptic imagery', 'Analyses why the quiet ending is thematically significant'],
      relevantQuoteIds: ['q-e-bang-whimper', 'q-e-the-shadow'],
      strongerResponseHtml: 'A stronger response would connect this ending to the poem\'s opening ("hollow men… stuffed men") to show the anticlimax as the natural, earned conclusion of a poem about emptiness rather than a surprising twist.',
    },
    {
      id: 'sa-e-4',
      qtype: 'how',
      prompt: 'How does Eliot use the "Shadow" motif in "The Hollow Men" to develop the poem\'s central idea?',
      marks: 4,
      stimulusHtml: null,
      modelAnswerHtml: 'The capitalised "Shadow" recurs across four parallel binary pairings — "Between the idea / And the reality", "Between the motion / And the act" — using anaphoric repetition to insist that the gap between intention and action is total and inescapable, not occasional. By repeating the same structure across multiple different binaries (thought, creation, desire, existence), Eliot generalises the poem\'s paralysis from a single failure to a complete condition of being.',
      markingGuidanceHtml: 'Look for reference to the anaphoric/repeated structure specifically, and an explanation of how repetition across multiple binaries generalises the poem\'s central idea rather than illustrating it once.',
      keyPoints: ['Identifies the anaphoric repetition across binary pairings', 'Explains the generalising effect of the repeated structure', 'Connects to the poem\'s central paralysis theme'],
      relevantQuoteIds: ['q-e-the-shadow'],
      strongerResponseHtml: 'A stronger response would connect the Shadow motif back to Prufrock\'s individual paralysis, showing this poem extends the same idea to a collective scale.',
    },
    {
      id: 'sa-e-5',
      qtype: 'to-what-extent',
      prompt: 'To what extent does "Journey of the Magi" offer genuine hope in contrast to the earlier poems in Eliot\'s canon?',
      marks: 5,
      stimulusHtml: null,
      modelAnswerHtml: 'Journey of the Magi does mark a genuine shift — unlike Prufrock or the hollow men, the Magus actually undergoes transformation, glimpsing renewal at the "temperate valley" and its baptismal imagery. But the poem stops well short of offering comfortable hope: the Magus returns "no longer at ease" among "an alien people clutching their gods", and closes by admitting he "should be glad of another death". The poem therefore offers hope only in a qualified, costly form — redemption is real, but it permanently estranges the Magus from his old life rather than simply resolving his difficulties.',
      markingGuidanceHtml: 'Reward responses that identify BOTH the genuine shift toward hope AND its qualification/cost, rather than treating the poem as either purely hopeful or purely despairing. A strong response should engage with "to what extent" by weighing both sides.',
      keyPoints: ['Identifies the genuine shift toward transformation/hope', 'Identifies the qualification — estrangement, the death wish', 'Uses both the temperate-valley and "no longer at ease" quotes', 'Engages with "to what extent" rather than a one-sided answer'],
      relevantQuoteIds: ['q-e-temperate-valley', 'q-e-no-longer-at-ease'],
      strongerResponseHtml: 'A stronger response would extend this into an argument about Eliot\'s canon as a whole — that his poetic arc offers hope as something earned through loss, not as an escape from the earlier poems\' disillusionment.',
    },
  ],
  essayQuestions: [
    {
      id: 'essay-e-thesis-1',
      type: 'thesis',
      prompt: '"Eliot\'s poetry traces a single mind\'s journey from paralysis to redemption." To what extent is this true of the poems you have studied?',
      marks: null,
      suggestedEvidence: ['q-e-dare-disturb', 'q-e-bang-whimper', 'q-e-no-longer-at-ease'],
      modelThesisHtml:
        'Read as a body of work, Eliot\'s poems do trace a genuine arc from individual paralysis (Prufrock) through collective disillusionment (The Hollow Men) to a qualified, costly hope (Journey of the Magi) — but "redemption" understates how much that final poem insists on loss and estrangement as the price of spiritual change, rather than its opposite.',
      modelArgumentStructureHtml: 'Structure: (1) concede the genuine arc across the three poems (individual paralysis → collective paralysis → transformation); (2) complicate "redemption" specifically — the Magus\'s hope costs him his old life; (3) synthesise: Eliot\'s canon offers development, but refuses to make that development comfortable.',
      modelResponseHtml: 'A full response is not modelled at thesis-practice stage — see the full-essay question for a modelled response.',
      planningGuidanceHtml: 'Decode the question: "single mind\'s journey" is doing real work — a strong response should note that Eliot actually moves from an individual voice (Prufrock) to a collective one (The Hollow Men) before returning to an individual, if different, voice (the Magus) — the "journey" is not as simple or singular as the question implies.',
    },
    {
      id: 'essay-e-full-1',
      type: 'full-essay',
      prompt: 'Analyse how Eliot\'s formal choices — voice, structure and allusion — work together to shape his critique of modernity across the poems you have studied.',
      marks: 20,
      suggestedEvidence: ['q-e-etherised', 'q-e-coffee-spoons', 'q-e-dare-disturb', 'q-e-hollow-stuffed', 'q-e-the-shadow', 'q-e-bang-whimper', 'q-e-cold-coming', 'q-e-no-longer-at-ease'],
      modelThesisHtml:
        'Eliot\'s critique of modernity is inseparable from his formal choices — dramatic monologue and fragmented syntax do not simply describe psychological paralysis, they enact it for the reader, while his shift toward allusive, retrospective form in Journey of the Magi enacts an equally formal shift toward the possibility, though not the ease, of redemption.',
      modelArgumentStructureHtml: 'Suggested structure: (1) intro with thesis; (2) Prufrock — dramatic monologue and fragmented syntax formally enacting individual paralysis; (3) The Hollow Men — collective voice and anaphoric repetition generalising that paralysis, resolved through deliberate anticlimax; (4) Journey of the Magi — the shift to retrospective, allusive dramatic monologue formally enacting a hard-won, costly transformation; (5) conclusion on how form and idea are inseparable across the whole body of work.',
      modelResponseHtml:
        '<p>T.S. Eliot\'s critique of modernity across his early and middle poetry is never simply a matter of what his speakers say about the modern world — it is built into how the poems are constructed. Dramatic monologue, fragmented syntax, personification and allusion are not decorative techniques layered over a straightforward argument; they are the mechanism by which Eliot makes psychological paralysis, collective disillusionment and eventual, costly transformation legible to a reader, rather than simply describing these states from the outside.</p><p>"The Love Song of J. Alfred Prufrock" establishes this method from its opening simile, comparing the evening to "a patient etherised upon a table" — a jarringly clinical image that immediately rejects Romantic convention and signals that Eliot\'s modern world offers no comforting beauty. The poem\'s dramatic monologue form places the reader directly inside Prufrock\'s anxious consciousness, and its fragmented syntax formally enacts his hesitation: "Do I dare / Disturb the universe?" breaks across the line exactly where Prufrock\'s nerve breaks, so the reader experiences suspended uncertainty rather than being told about it. Even Prufrock\'s central symbol — "I have measured out my life with coffee spoons" — works through compression rather than statement, reducing an entire wasted life to a single small, repeated domestic object.</p><p>"The Hollow Men" extends this same formal logic from an individual to a collective scale. Where Prufrock speaks in a singular, anxious "I", the hollow men speak only as "we" — "We are the hollow men / We are the stuffed men" — and the droning anaphoric repetition of this opening enacts the very emptiness it describes, stripping the collective of any individuating voice at all. This formal generalisation continues through the poem\'s central motif: the capitalised "Shadow" that "falls" between four separate binary pairings (idea/reality, motion/act, conception/creation, desire/existence) uses repeated structure to insist that the gap between intention and action is total, not occasional. The poem\'s famous closing anticlimax — "Not with a bang but a whimper" — is the logical formal conclusion of this pattern: a poem built entirely from repetition and negation can only end in deflation, never in dramatic resolution, because dramatic resolution would require exactly the decisive action the hollow men are formally incapable of.</p><p>"Journey of the Magi", written after Eliot\'s 1927 conversion to Anglicanism, marks a genuine formal shift that mirrors its thematic one. Where Prufrock and the hollow men speak from inside their own unresolved present, the Magus narrates retrospectively, opening with an allusion to a real 1622 Nativity sermon — "A cold coming we had of it" — that immediately establishes distance and reflection rather than raw, unresolved anxiety. This formal detachment allows Eliot to represent genuine transformation: the Magus recalls a real, concrete vision of renewal at "a temperate valley… with a running stream and a water-mill", its baptismal imagery working through allusion exactly as Prufrock\'s clinical simile or the hollow men\'s scarecrow imagery did earlier. Yet Eliot refuses to let this formal shift resolve into simple comfort. The poem\'s closing lines — the Magus "no longer at ease here… with an alien people clutching their gods" — use the same technique of concrete, allusive imagery to insist that transformation has cost him his old life entirely, not simply improved it.</p><p>Across all three poems, then, Eliot\'s formal choices are never separable from his ideas about modernity. Fragmented syntax and dramatic monologue enact individual paralysis; anaphoric repetition and collective voice generalise that paralysis into a post-war condition; and a shift toward retrospective, allusive form enacts a transformation that is genuine but costly. Eliot\'s critique of modernity, in other words, is not something his poems argue — it is something they formally perform.</p>',
      planningGuidanceHtml: 'Decode the question: "voice, structure and allusion" gives you a built-in three-part structure across the three poems — use it deliberately rather than discussing technique and theme separately. For each poem, name the SPECIFIC formal choice and explain how it enacts (not just describes) that poem\'s particular stage in the paralysis-to-redemption arc.',
    },
  ],
}
