import type { EvidenceQuote } from '../../lib/content/paper1'
import { NINETEEN_EIGHTY_FOUR } from './common-module-1984'
import type { EnglishQuote } from '../../lib/content/english'

/**
 * The Paper 1 evidence bank for Nineteen Eighty-Four — spec section 4/20:
 * broader than the core quote bank (13 quotes, mostly Part One), and kept
 * SEPARATE from it rather than replacing it. Reused quotes below reference
 * the core bank's own analysis (via `fromExistingQuote`) instead of
 * re-authoring it; genuinely new quotes (`existingQuoteId: null`) are
 * sourced from Part One, Two AND Three, across five different
 * speakers/sources (Winston, Julia, O'Brien, the narrator, and the
 * telescreen voice), specifically to avoid clustering practice quotes
 * around the same handful already used for essay revision.
 *
 * Chapter numbers are given only where I could place the scene with real
 * confidence; two entries below are Part-level only rather than guessed
 * (spec section 5 — don't invent chapter locations).
 */

const CHAPTER_MAP: Record<string, [part: number, chapter: number | null]> = {
  'q-opening-line': [1, 1],
  'q-war-is-peace': [1, 1],
  'q-bb-watching': [1, 1],
  'q-down-with-bb': [1, 1],
  'q-who-controls-past': [1, null],
  'q-cubic-centimetres': [1, 7],
  'q-hope-proles': [1, 7],
  'q-two-plus-two': [1, 7],
  'q-sanity-not-statistical': [1, 7],
  'q-never-rebel': [1, 7],
  'q-we-are-the-dead': [2, 10],
  'q-loved-big-brother': [3, 6],
  'q-doublethink': [2, 9],
}

function fromExistingQuote(quote: EnglishQuote): EvidenceQuote {
  const [part, chapter] = CHAPTER_MAP[quote.id] ?? [null, null]
  return {
    id: `evidence-${quote.id}`,
    text: quote.textHtml,
    textId: 'nineteen-eighty-four',
    location: quote.location,
    part,
    chapter,
    speaker: quote.speaker,
    techniqueIds: quote.techniqueIds,
    themeIds: quote.themeIds,
    context: quote.contextHtml,
    effect: quote.argumentHtml,
    meaning: quote.revealsHtml,
    authorialPurpose: quote.authorialPurposeHtml,
    existingQuoteId: quote.id,
  }
}

const REUSED_EVIDENCE: EvidenceQuote[] = NINETEEN_EIGHTY_FOUR.quotes.map(fromExistingQuote)

const NEW_EVIDENCE: EvidenceQuote[] = [
  {
    id: 'e-two-minutes-hate',
    text: 'A hideous ecstasy of fear and vindictiveness, a desire to kill, to torture, to smash faces in with a sledge-hammer, seemed to flow through the whole group of people like an electric current.',
    textId: 'nineteen-eighty-four',
    location: 'Part One, Chapter 1',
    part: 1,
    chapter: 1,
    speaker: null,
    techniqueIds: ['t-simile', 't-kinaesthetic-imagery', 't-listing'],
    themeIds: ['t-control'],
    context: "The narrator's description of the crowd's reaction during the daily Two Minutes Hate, a ritual public screening that whips Party members into collective fury against an enemy figure.",
    effect: "The simile ('like an electric current') presents the crowd's violence as a single, instantaneous force running through many bodies at once, while the asyndetic list of violent verbs ('kill, to torture, to smash') accumulates the intensity of that violence without pause.",
    meaning: 'The Party manufactures and channels raw human aggression into a controlled, collective ritual, showing that its power rests on manipulating emotion en masse, not just individual coercion.',
    authorialPurpose: "Orwell wants the reader to feel how quickly individual restraint dissolves into mob violence when engineered by the state, making the Two Minutes Hate a chilling demonstration of psychological control rather than an abstract claim about propaganda.",
    existingQuoteId: null,
  },
  {
    id: 'e-truth-alteration',
    text: 'This process of continuous alteration was applied not only to newspapers, but to books, periodicals, pamphlets, posters, leaflets, films, soundtracks, cartoons, photographs — to every kind of literature or documentation which might conceivably hold any political or ideological significance.',
    textId: 'nineteen-eighty-four',
    location: 'Part One, Chapter 4',
    part: 1,
    chapter: 4,
    speaker: null,
    techniqueIds: ['t-listing'],
    themeIds: ['t-truth-memory'],
    context: "The narrator describes the scope of Winston's work at the Ministry of Truth, rewriting historical records to match the Party's current version of events.",
    effect: 'The extended asyndetic list overwhelms the reader with the sheer range of media forms being falsified, making the falsification feel total and inescapable rather than an isolated act.',
    meaning: 'No form of recorded history is exempt from the Party\'s control — the past exists only in whatever form the Party currently permits it to exist in.',
    authorialPurpose: "Orwell itemises the list exhaustively so the reader — like Winston — cannot find a corner of the historical record the Party has left untouched, reinforcing the novel's central claim that controlling the past is inseparable from controlling the present.",
    existingQuoteId: null,
  },
  {
    id: 'e-poster-gazed',
    text: 'On each landing, opposite the lift shaft, the poster with the enormous face gazed from the wall.',
    textId: 'nineteen-eighty-four',
    location: 'Part One, Chapter 1',
    part: 1,
    chapter: 1,
    speaker: null,
    techniqueIds: ['t-personification', 't-visual-imagery'],
    themeIds: ['t-control'],
    context: "Part of the narrator's description of Victory Mansions as Winston climbs the stairs to his flat, establishing the omnipresence of Big Brother's image.",
    effect: 'Personifying the poster as something that "gazed" gives a static image an active, watching presence, so surveillance feels alive and directed rather than passive decoration.',
    meaning: 'Even inanimate Party imagery is constructed to feel like it is actively monitoring citizens, collapsing the distinction between propaganda and literal surveillance.',
    authorialPurpose: "Orwell personifies the poster specifically (rather than simply stating 'the poster was on the wall') so that the reader shares Winston's felt sense of being watched everywhere, before the telescreen's actual surveillance capability is even explained.",
    existingQuoteId: null,
  },
  {
    id: 'e-julia-next-generation',
    text: "I'm not interested in the next generation, dear, I'm interested in us.",
    textId: 'nineteen-eighty-four',
    location: 'Part Two',
    part: 2,
    chapter: null,
    speaker: 'Julia',
    techniqueIds: ['t-characterisation', 't-contrast'],
    themeIds: ['t-rebellion'],
    context: "Julia's response to Winston during one of their meetings in the room above Mr Charrington's shop, when he raises the possibility of joining an organised resistance for the sake of the future.",
    effect: 'The blunt, direct rejection of the "next generation" contrasts sharply with Winston\'s more politically and historically minded rebellion, characterising Julia\'s resistance as personal and immediate rather than ideological.',
    meaning: 'Rebellion against the Party can take radically different forms — Julia\'s hedonistic, present-focused defiance is just as real as Winston\'s intellectual one, but neither proves durable against the Party\'s methods.',
    authorialPurpose: "Orwell differentiates Julia's motivations from Winston's so that their shared fate at the end of the novel indicts the Party's total control regardless of why or how a citizen chooses to resist.",
    existingQuoteId: null,
  },
  {
    id: 'e-three-kinds-of-people',
    text: 'Throughout recorded time, and probably since the end of the Neolithic Age, there have been three kinds of people in the world, the High, the Middle, and the Low.',
    textId: 'nineteen-eighty-four',
    location: 'Part Two, Chapter 9',
    part: 2,
    chapter: 9,
    speaker: null,
    techniqueIds: ['t-listing', 't-tone'],
    themeIds: ['t-control'],
    context: "The opening of the chapter from Goldstein's book, 'The Theory and Practice of Oligarchical Collectivism', that Winston reads, explaining the historical structure of power.",
    effect: "The confident, almost textbook-like triadic listing ('the High, the Middle, and the Low') gives the Party's account of social hierarchy the tone of settled historical fact rather than ideology.",
    meaning: 'The Party frames its own hierarchical power structure as an unchangeable law of history, not a political choice — naturalising its rule.',
    authorialPurpose: "By having this appear as an extract from a book-within-the-book, Orwell lets the Party's own theory of power speak in its own voice, exposing its logic directly to the reader rather than filtering it through Winston's suspicion.",
    existingQuoteId: null,
  },
  {
    id: 'e-war-internal',
    text: 'War, it will be seen, is now a purely internal affair.',
    textId: 'nineteen-eighty-four',
    location: 'Part Two, Chapter 9',
    part: 2,
    chapter: 9,
    speaker: null,
    techniqueIds: ['t-paradox', 't-irony'],
    themeIds: ['t-control', 't-truth-memory'],
    context: "Also from Goldstein's book, explaining that the perpetual war between Oceania, Eurasia and Eastasia is not fought to be won, but to keep each population impoverished and obedient.",
    effect: "The paradox of a 'war' that is 'internal' rather than fought against an external enemy overturns the reader's assumption about what war is for, exposing it as a domestic control mechanism rather than a geopolitical contest.",
    meaning: 'The Party maintains permanent scarcity and fear not despite the war, but because of it — war is a tool of internal discipline, not defence.',
    authorialPurpose: 'Orwell uses this paradox to make explicit one of the novel\'s bleakest claims: that a state can manufacture external threat purely to control its own population, a warning aimed squarely at Cold War-era propaganda.',
    existingQuoteId: null,
  },
  {
    id: 'e-iron-voice',
    text: '"You are the dead," said an iron voice behind them.',
    textId: 'nineteen-eighty-four',
    location: 'Part Two, Chapter 10',
    part: 2,
    chapter: 10,
    speaker: 'Telescreen voice',
    techniqueIds: ['t-auditory-imagery', 't-irony'],
    themeIds: ['t-rebellion', 't-control'],
    context: "Immediately after Winston and Julia each say 'We are the dead' to one another, a hidden telescreen behind a picture in their rented room repeats the phrase back at them, revealing they have been watched and are about to be arrested.",
    effect: "The harsh auditory imagery of an 'iron voice' — cold, mechanical, without individual identity — makes the Party's surveillance sound literally inhuman, arriving as confirmation of what Winston had already, fatalistically, said about himself.",
    meaning: "The Party doesn't just observe Winston and Julia's rebellion — it lets them speak their own doom aloud first, then repeats it back, demonstrating total control over even the moment of their own self-awareness.",
    authorialPurpose: "Orwell has the Party echo Winston's own words rather than invent new ones, making the irony land harder: the surveillance state's power lies in confirmation, not invention.",
    existingQuoteId: null,
  },
  {
    id: 'e-power-not-a-means',
    text: 'Power is not a means, it is an end.',
    textId: 'nineteen-eighty-four',
    location: 'Part Three, Chapter 3',
    part: 3,
    chapter: 3,
    speaker: "O'Brien",
    techniqueIds: ['t-antithesis', 't-characterisation'],
    themeIds: ['t-control'],
    context: "During Winston's interrogation in the Ministry of Love, O'Brien explains — with disarming honesty — the Party's true motive, stripped of the propaganda Winston has spent the novel trying to see past.",
    effect: 'The antithetical structure ("not a means… it is an end") flatly rejects the conventional justification that power serves some other good, forcing the two ideas into direct, symmetrical opposition so there is no room left for Winston to argue otherwise.',
    meaning: "The Party's rule is not a corrupted attempt at a better society — it is straightforwardly about power for its own sake, with no further justification required or offered.",
    authorialPurpose: "Orwell gives O'Brien this blunt clarity deliberately: it is more disturbing than any lie, because it shows the Party doesn't even need to deceive itself about its own motives.",
    existingQuoteId: null,
  },
  {
    id: 'e-seeks-power',
    text: 'The Party seeks power entirely for its own sake.',
    textId: 'nineteen-eighty-four',
    location: 'Part Three, Chapter 3',
    part: 3,
    chapter: 3,
    speaker: "O'Brien",
    techniqueIds: ['t-tone', 't-irony'],
    themeIds: ['t-control'],
    context: "O'Brien continues his explanation of Party doctrine to Winston during interrogation, immediately following his claim that power is an end in itself.",
    effect: "The plain, declarative tone — with no hedging or justification — makes the admission feel more chilling than a passionate defence would, since it shows total confidence that no argument against it is possible.",
    meaning: "The Party has moved entirely beyond needing to justify itself, even privately, revealing the endpoint of totalitarian control: it doesn't require belief in its own goodness, only obedience.",
    authorialPurpose: 'Orwell positions this admission late in the novel, after Winston (and the reader) have spent two parts assuming there must be a deeper rationale, so the plainness of the statement lands as a genuine escalation of horror.',
    existingQuoteId: null,
  },
  {
    id: 'e-worst-thing',
    text: '"The worst thing in the world," said O\'Brien, "varies from individual to individual."',
    textId: 'nineteen-eighty-four',
    location: 'Part Three, Chapter 5',
    part: 3,
    chapter: 5,
    speaker: "O'Brien",
    techniqueIds: ['t-tone', 't-foreshadowing'],
    themeIds: ['t-control'],
    context: "O'Brien introduces Room 101 to Winston, explaining the concept behind the Ministry of Love's final, personalised method of psychological destruction.",
    effect: "O'Brien's calm, almost clinical tone in describing what is about to be an act of extreme cruelty makes the Party's method feel bureaucratically routine rather than exceptional, while the vague phrasing foreshadows a horror the reader (and Winston) cannot yet picture.",
    meaning: "The Party's control is total enough to be individually tailored — it doesn't need one universal method of breaking a person, because it has already catalogued each person's specific fear.",
    authorialPurpose: 'Orwell withholds the specific content of Room 101 at this point deliberately, using O\'Brien\'s clinical tone to build dread through restraint rather than graphic description.',
    existingQuoteId: null,
  },
  {
    id: 'e-do-it-to-julia',
    text: 'Do it to Julia!',
    textId: 'nineteen-eighty-four',
    location: 'Part Three, Chapter 5',
    part: 3,
    chapter: 5,
    speaker: 'Winston Smith',
    techniqueIds: ['t-short-sentences', 't-irony'],
    themeIds: ['t-rebellion', 't-control'],
    context: "Winston's scream in Room 101, faced with his own worst fear (rats), betraying Julia to save himself.",
    effect: 'The short, exclamatory fragment — stripped of any qualification or hesitation — makes Winston\'s betrayal instantaneous and total, with no room left in the sentence for the internal conflict a longer, hedged sentence might have suggested.',
    meaning: "The Party's methods can override even the deepest personal loyalty in an instant, once a person's specific, individualised fear is engaged.",
    authorialPurpose: "Orwell chooses the starkest possible sentence for the novel's true turning point, so that the brevity itself embodies how completely and immediately Winston's resistance collapses.",
    existingQuoteId: null,
  },
  {
    id: 'e-won-victory',
    text: 'He had won the victory over himself.',
    textId: 'nineteen-eighty-four',
    location: 'Part Three, Chapter 6',
    part: 3,
    chapter: 6,
    speaker: null,
    techniqueIds: ['t-irony'],
    themeIds: ['t-control', 't-rebellion'],
    context: "The narrator's description of Winston's state of mind in the novel's final pages, shortly before the closing line, as he sits at the Chestnut Tree Café.",
    effect: 'Framing total psychological defeat as a "victory" is starkly ironic — the language of triumph is applied to the complete erasure of Winston\'s independent selfhood, with no gap left for the reader to read it as anything but the Party\'s own propaganda internalised.',
    meaning: "Winston's re-education has succeeded so completely that he now narrates his own destruction using the Party's own inverted logic, without any trace of the resistance he once had.",
    authorialPurpose: "Orwell uses this ironic inversion to deny the reader any ambiguity about the ending — this is not a partial defeat open to interpretation, but total capitulation described, chillingly, in the language of success.",
    existingQuoteId: null,
  },
]

export const PAPER_ONE_EVIDENCE: EvidenceQuote[] = [...REUSED_EVIDENCE, ...NEW_EVIDENCE]
