import type { EnglishTechnique } from '../../lib/content/english'
import { NINETEEN_EIGHTY_FOUR } from './common-module-1984'

/**
 * The Paper 1 Language Technique Bank — broader than any single text's
 * technique list (english.ts's EnglishText.techniques), because Paper 1
 * also covers unseen prose, poetry, persuasive and visual/multimodal texts
 * that Nineteen Eighty-Four alone doesn't exercise. Deliberately NOT an
 * exhaustive glossary (spec section 3 warns against that): every entry
 * here is one actually worth testing at Paper 1, organised into the
 * categories that matter for that paper specifically.
 *
 * The 10 techniques already modelled against Nineteen Eighty-Four are
 * reused by id, not re-authored — this bank is a superset, not a fork.
 * Their `exampleQuoteId`s are remapped from the core quote bank's ids to
 * the Paper 1 evidence bank's `evidence-` prefixed ids (see
 * paper1-evidence-bank.ts's `fromExistingQuote`), so the same underlying
 * quotation resolves correctly in both banks without being duplicated.
 */
const REMAPPED_CORE_TECHNIQUES: EnglishTechnique[] = NINETEEN_EIGHTY_FOUR.techniques.map((t) => ({
  ...t,
  exampleQuoteId: t.exampleQuoteId ? `evidence-${t.exampleQuoteId}` : null,
}))

export const PAPER_ONE_TECHNIQUES: EnglishTechnique[] = [
  ...REMAPPED_CORE_TECHNIQUES,

  // ---- Figurative language ----
  {
    id: 't-metaphor',
    name: 'Metaphor',
    category: 'figurative-language',
    definitionHtml: 'A direct comparison that equates one thing with another, without using "like" or "as".',
    effectHtml: 'Forces two unlike ideas into a single image, compressing a complex comparison into a few words.',
    whyAuthorsUseItHtml: 'Writers reach for metaphor when a literal description would be flatter or slower than an equating image.',
    exampleQuoteId: null,
    genericExampleHtml: '"Time is a thief" equates time directly with a thief, without "like" or "as".',
    analyticalLanguage: ['equates', 'constructs', 'frames … as', 'collapses the distinction between'],
    howToRecogniseHtml: 'One thing is directly called or equated with another unlike thing — no "like"/"as" bridging word.',
    commonMistakeHtml: 'Calling any comparison a metaphor — check first whether "like" or "as" is present (that\'s a simile, not a metaphor).',
    confusedWithIds: ['t-simile', 't-personification', 't-symbolism'],
  },
  {
    id: 't-simile',
    name: 'Simile',
    category: 'figurative-language',
    definitionHtml: 'A comparison between two unlike things using "like" or "as".',
    effectHtml: 'Makes an unfamiliar feeling or idea concrete by anchoring it to something the reader already knows.',
    whyAuthorsUseItHtml: 'Useful when the writer wants the comparison itself to be visible/foregrounded, rather than fully fused as in a metaphor.',
    exampleQuoteId: 'e-two-minutes-hate',
    genericExampleHtml: null,
    analyticalLanguage: ['likens … to', 'draws a comparison between', 'evokes … through the simile'],
    howToRecogniseHtml: 'Look for the explicit connective word "like" or "as" joining two unlike things.',
    commonMistakeHtml: 'Skipping past "seemed to flow … like an electric current" as just imagery — the "like" makes this specifically a simile, worth naming precisely.',
    confusedWithIds: ['t-metaphor'],
  },
  {
    id: 't-personification',
    name: 'Personification',
    category: 'figurative-language',
    definitionHtml: 'Giving human qualities, actions or feelings to a non-human thing.',
    effectHtml: 'Makes an inanimate object feel active and threatening (or comforting) rather than passive.',
    whyAuthorsUseItHtml: 'Lets an object seem to act with intent, which is often the point when the object represents institutional or ideological power.',
    exampleQuoteId: 'e-poster-gazed',
    genericExampleHtml: null,
    analyticalLanguage: ['personifies', 'animates', 'lends agency to', 'anthropomorphises'],
    howToRecogniseHtml: 'A verb normally reserved for living things (gazed, watched, whispered, waited) is given to an object or abstract idea.',
    commonMistakeHtml: 'Missing quieter personification (a poster that "gazes") because it isn\'t as obvious as a talking object.',
    confusedWithIds: ['t-metaphor', 't-symbolism'],
  },
  {
    id: 't-hyperbole',
    name: 'Hyperbole',
    category: 'figurative-language',
    definitionHtml: 'Deliberate, obvious exaggeration, not meant to be taken literally.',
    effectHtml: 'Amplifies emotional intensity or urgency beyond what a literal statement could achieve.',
    whyAuthorsUseItHtml: 'Used when the writer wants the reader to feel the scale of a feeling or claim, not just register a fact.',
    exampleQuoteId: null,
    genericExampleHtml: '"I\'ve told you a million times" exaggerates frequency for emotional emphasis, not literal accuracy.',
    analyticalLanguage: ['exaggerates', 'amplifies', 'overstates … for effect'],
    howToRecogniseHtml: 'A claim that is obviously, deliberately beyond literal truth ("a million times", "the whole world stopped").',
    commonMistakeHtml: 'Calling ordinary intensifying language ("very", "extremely") hyperbole — hyperbole specifically exaggerates past what is literally believable.',
    confusedWithIds: [],
  },
  {
    id: 't-metonymy',
    name: 'Metonymy',
    category: 'figurative-language',
    definitionHtml: 'Referring to something by a closely associated term rather than its own name (e.g. "the Crown" for the monarchy).',
    effectHtml: 'Lets an abstract institution or system be referred to as though it were a single, unified thing.',
    whyAuthorsUseItHtml: 'Useful for compressing a large, faceless system into one graspable name a reader can hold onto.',
    exampleQuoteId: null,
    genericExampleHtml: '"Big Brother" functions partly as metonymy for the Party\'s entire surveillance apparatus, not literally one person.',
    analyticalLanguage: ['stands in for', 'is metonymic for', 'substitutes … for the wider institution of'],
    howToRecogniseHtml: 'A specific name or image is used to represent a larger, related system or institution.',
    commonMistakeHtml: 'Confusing metonymy with symbolism — metonymy substitutes a closely associated name; symbolism uses an object to represent an abstract idea, not necessarily a related one.',
    confusedWithIds: ['t-symbolism'],
  },

  // ---- Sound ----
  {
    id: 't-alliteration',
    name: 'Alliteration',
    category: 'sound',
    definitionHtml: 'The repetition of the same consonant sound at the start of nearby words.',
    effectHtml: 'Creates a rhythmic emphasis that draws the reader\'s attention to the linked words.',
    whyAuthorsUseItHtml: 'Used to bind ideas together sonically, making a phrase more memorable or forceful.',
    exampleQuoteId: null,
    genericExampleHtml: '"Ripe, red raspberry" repeats the initial "r" sound, binding the words together and emphasising the fruit\'s richness.',
    analyticalLanguage: ['the alliterative repetition of', 'binds … together sonically', 'emphasises through alliteration'],
    howToRecogniseHtml: 'Two or more nearby words start with the same consonant sound (not just letter — check the sound).',
    commonMistakeHtml: 'Naming alliteration without quoting the actual repeated sound, or confusing it with assonance (vowel sounds) or sibilance (specifically "s" sounds).',
    confusedWithIds: ['t-assonance', 't-sibilance'],
  },
  {
    id: 't-sibilance',
    name: 'Sibilance',
    category: 'sound',
    definitionHtml: 'The repetition of "s" (or soft "sh"/"z") sounds in close succession.',
    effectHtml: 'Often creates a hissing, whispering or unsettling aural quality.',
    whyAuthorsUseItHtml: 'Used when the writer wants a passage to sound quiet, sinister, or slippery, reinforced at the level of sound rather than meaning.',
    exampleQuoteId: null,
    genericExampleHtml: '"The soft, hissing silence settled" repeats "s" sounds to create an unsettling quiet.',
    analyticalLanguage: ['the sibilant repetition of', 'creates a hissing quality through'],
    howToRecogniseHtml: 'Repeated "s"/soft-"c"/"z" sounds clustered in a short phrase.',
    commonMistakeHtml: 'Calling any repeated consonant sibilance — it specifically refers to "s"-family sounds, not consonants in general (that\'s alliteration).',
    confusedWithIds: ['t-alliteration'],
  },
  {
    id: 't-assonance',
    name: 'Assonance',
    category: 'sound',
    definitionHtml: 'The repetition of vowel sounds within nearby words (not necessarily at the start).',
    effectHtml: 'Creates internal musicality or slows/quickens the rhythm of a line.',
    whyAuthorsUseItHtml: 'Especially common in poetry, where sound patterning reinforces mood without needing rhyme.',
    exampleQuoteId: null,
    genericExampleHtml: '"The light of the fire is a sight" repeats the long "i" sound across several words.',
    analyticalLanguage: ['the assonant echo of', 'reinforces … through internal vowel repetition'],
    howToRecogniseHtml: 'The same vowel SOUND (not spelling) repeats within a short stretch of text — say the words aloud.',
    commonMistakeHtml: 'Confusing spelling with sound ("fair" and "hair" share letters but not necessarily the exact vowel sound in every accent) — assonance is about sound.',
    confusedWithIds: ['t-alliteration'],
  },
  {
    id: 't-onomatopoeia',
    name: 'Onomatopoeia',
    category: 'sound',
    definitionHtml: 'A word that phonetically imitates the sound it describes.',
    effectHtml: 'Lets the reader almost hear the sound being described, rather than just being told about it.',
    whyAuthorsUseItHtml: 'Adds immediate sensory immediacy, especially in action or setting description.',
    exampleQuoteId: null,
    genericExampleHtml: '"The engine roared and clanked" — "roared" and "clanked" imitate the sounds they name.',
    analyticalLanguage: ['the onomatopoeic', 'mimics the sound of', 'renders … audible through'],
    howToRecogniseHtml: 'A single word that sounds like the noise it refers to (bang, hiss, clatter, buzz).',
    commonMistakeHtml: 'Identifying onomatopoeia and stopping there — the analysis needs to say what the imitated sound contributes to mood or setting.',
    confusedWithIds: [],
  },

  // ---- Imagery ----
  {
    id: 't-visual-imagery',
    name: 'Visual Imagery',
    category: 'imagery',
    definitionHtml: 'Descriptive language that creates a picture the reader can visualise.',
    effectHtml: 'Lets the reader see the scene rather than simply being informed of it.',
    whyAuthorsUseItHtml: 'Used to ground abstract ideas in a concrete, visualisable scene.',
    exampleQuoteId: 'e-poster-gazed',
    genericExampleHtml: null,
    analyticalLanguage: ['visually renders', 'paints a picture of', 'makes visible'],
    howToRecogniseHtml: 'Description specifically appealing to sight — colour, shape, size, movement.',
    commonMistakeHtml: 'Using "imagery" as a catch-all when the sense being appealed to is specifically sight — naming "visual imagery" is more precise and more markable.',
    confusedWithIds: ['t-imagery', 't-symbolism'],
  },
  {
    id: 't-auditory-imagery',
    name: 'Auditory Imagery',
    category: 'imagery',
    definitionHtml: 'Descriptive language that appeals specifically to the sense of hearing.',
    effectHtml: 'Lets the reader hear a scene, often reinforcing atmosphere (harsh, soothing, oppressive).',
    whyAuthorsUseItHtml: 'Particularly useful for building atmosphere in a scene that doesn\'t rely on visual description alone.',
    exampleQuoteId: 'e-iron-voice',
    genericExampleHtml: null,
    analyticalLanguage: ['renders audible', 'evokes the sound of', 'appeals to the reader\'s hearing'],
    howToRecogniseHtml: 'Description of sound — tone of voice, volume, pitch, or a described noise.',
    commonMistakeHtml: 'Missing auditory imagery embedded in dialogue tags ("an iron voice") because it looks like plain narration rather than deliberate imagery.',
    confusedWithIds: ['t-imagery'],
  },
  {
    id: 't-kinaesthetic-imagery',
    name: 'Kinaesthetic Imagery',
    category: 'imagery',
    definitionHtml: 'Descriptive language that evokes bodily movement or physical sensation.',
    effectHtml: 'Makes an emotional or ideological state feel physically real, embodied rather than abstract.',
    whyAuthorsUseItHtml: 'Especially effective for depicting collective or visceral states (mob violence, physical fear) that a purely intellectual description couldn\'t convey.',
    exampleQuoteId: 'e-two-minutes-hate',
    genericExampleHtml: null,
    analyticalLanguage: ['renders physically visceral', 'embodies … through kinaesthetic imagery'],
    howToRecogniseHtml: 'Description of physical movement, force, or bodily sensation (to smash, to kill, trembling, straining).',
    commonMistakeHtml: 'Treating any violent word as automatically kinaesthetic imagery — check that it specifically evokes movement/physical sensation, not just violent meaning.',
    confusedWithIds: ['t-imagery'],
  },

  // ---- Structure and syntax ----
  {
    id: 't-anaphora',
    name: 'Anaphora',
    category: 'structure-and-form',
    definitionHtml: 'The repetition of the same word or phrase at the START of successive clauses or sentences.',
    effectHtml: 'Builds rhythmic, escalating emphasis across a passage, often mimicking rhetorical or oratorical speech.',
    whyAuthorsUseItHtml: 'Common in persuasive and political language because the repeated opening drives a cumulative, hammering effect.',
    exampleQuoteId: null,
    genericExampleHtml: '"We shall fight. We shall never surrender." repeats "We shall" at the start of each clause.',
    analyticalLanguage: ['the anaphoric repetition of', 'builds rhetorical momentum through'],
    howToRecogniseHtml: 'The exact same word(s) begin two or more consecutive clauses or sentences.',
    commonMistakeHtml: 'Calling any repetition anaphora — anaphora specifically means the repeated element is at the START of each clause.',
    confusedWithIds: ['t-repetition'],
  },
  {
    id: 't-listing',
    name: 'Listing / Asyndeton',
    category: 'structure-and-form',
    definitionHtml: 'A series of three or more items, often without connecting conjunctions (asyndeton), placed in quick succession.',
    effectHtml: 'Creates a sense of overwhelming scale, thoroughness, or breathlessness by accumulating items rapidly.',
    whyAuthorsUseItHtml: 'Useful for conveying the totality of a system or the intensity of a feeling — the list itself performs "there is too much to fully take in".',
    exampleQuoteId: 'e-truth-alteration',
    genericExampleHtml: null,
    analyticalLanguage: ['the accumulative listing of', 'the asyndetic list of', 'builds a sense of totality through'],
    howToRecogniseHtml: 'Three or more items strung together, often with commas rather than "and" between each (asyndeton).',
    commonMistakeHtml: 'Just naming the list without explaining what the accumulation itself communicates (scale, exhaustion, totality).',
    confusedWithIds: ['t-anaphora'],
  },
  {
    id: 't-short-sentences',
    name: 'Short / Fragmented Sentences',
    category: 'structure-and-form',
    definitionHtml: 'Deliberately brief sentences (or sentence fragments) used for emphasis or pace.',
    effectHtml: 'Abruptly slows or punctuates the rhythm, often signalling shock, finality, or emotional collapse.',
    whyAuthorsUseItHtml: 'A sudden short sentence after longer ones draws maximum attention to a single moment.',
    exampleQuoteId: 'e-do-it-to-julia',
    genericExampleHtml: null,
    analyticalLanguage: ['the abrupt brevity of', 'punctuates … with a fragmented sentence'],
    howToRecogniseHtml: 'A noticeably short sentence (or incomplete one) placed among longer surrounding sentences.',
    commonMistakeHtml: 'Describing a short sentence as just "easy to read" — the effect is about emphasis and pace, not readability.',
    confusedWithIds: [],
  },
  {
    id: 't-rhetorical-question',
    name: 'Rhetorical Question',
    category: 'structure-and-form',
    definitionHtml: 'A question posed for effect, not to elicit an actual answer.',
    effectHtml: 'Invites the reader/listener to arrive at the (usually obvious) answer themselves, making them complicit in the argument.',
    whyAuthorsUseItHtml: 'Especially common in persuasive texts, where it feels less didactic than simply stating the point.',
    exampleQuoteId: null,
    genericExampleHtml: '"Isn\'t it time we demanded better?" doesn\'t seek information — it pushes the audience toward agreement.',
    analyticalLanguage: ['positions the reader to', 'the rhetorical question invites'],
    howToRecogniseHtml: 'A question mark, where the writer clearly isn\'t expecting or waiting for a literal answer.',
    commonMistakeHtml: 'Treating every question in a text as rhetorical — check whether a character is genuinely asking for information first.',
    confusedWithIds: [],
  },
  {
    id: 't-antithesis',
    name: 'Antithesis / Parallelism',
    category: 'structure-and-form',
    definitionHtml: 'A balanced grammatical structure that places contrasting ideas directly opposite each other.',
    effectHtml: 'The symmetry of the structure makes the contrast (or, ironically, the equivalence) feel definitive and quotable.',
    whyAuthorsUseItHtml: 'A precise, memorable way to state that two things are opposites (or, unsettlingly, treated as the same).',
    exampleQuoteId: 'e-power-not-a-means',
    genericExampleHtml: null,
    analyticalLanguage: ['the antithetical structure of', 'balances … against', 'the parallel construction of'],
    howToRecogniseHtml: 'Two clauses with matching grammar, built around a contrasting or reversed pair of ideas ("X is not Y, X is Z").',
    commonMistakeHtml: 'Confusing antithesis (a specific balanced grammatical structure) with juxtaposition (any contrasting placement, not necessarily grammatically balanced).',
    confusedWithIds: ['t-juxtaposition'],
  },
  {
    id: 't-contrast',
    name: 'Contrast',
    category: 'structure-and-form',
    definitionHtml: 'Placing two different ideas, images or characters in relation to highlight their difference.',
    effectHtml: 'Sharpens the reader\'s understanding of each side by measuring it against its opposite.',
    whyAuthorsUseItHtml: 'A broader, less structurally specific tool than antithesis — useful whenever difference itself is the point, without needing exact grammatical symmetry.',
    exampleQuoteId: null,
    genericExampleHtml: 'Contrasting Winston\'s private diary-writing with the Party\'s public slogans highlights individual thought against collective doctrine.',
    analyticalLanguage: ['contrasts … with', 'is thrown into relief against'],
    howToRecogniseHtml: 'Two elements are placed in relation specifically to highlight how different they are — broader than juxtaposition\'s "side by side" or antithesis\'s grammatical balance.',
    commonMistakeHtml: 'Using "contrast" so loosely it stops being a specific technique — name exactly what is being contrasted with what.',
    confusedWithIds: ['t-juxtaposition', 't-antithesis'],
  },

  // ---- Persuasive language (also relevant to unseen texts) ----
  {
    id: 't-modality',
    name: 'Modality',
    category: 'persuasive-language',
    definitionHtml: 'Language that expresses degrees of certainty, obligation or necessity (e.g. "must", "should", "might").',
    effectHtml: 'High modality asserts something as certain or compulsory; low modality softens a claim into a suggestion.',
    whyAuthorsUseItHtml: 'A precise tool for controlling how forcefully a claim lands, independent of the claim\'s actual content.',
    exampleQuoteId: null,
    genericExampleHtml: '"We must act now" (high modality) versus "We might consider acting" (low modality) — same idea, very different force.',
    analyticalLanguage: ['the high modality of', 'the low-modality hedging of', 'asserts … with certainty'],
    howToRecogniseHtml: 'A modal verb or adverb (must, should, will, might, possibly, certainly) attached to a claim.',
    commonMistakeHtml: 'Spotting a modal verb but not saying whether it raises or lowers certainty, and why that matters for persuasion.',
    confusedWithIds: [],
  },
  {
    id: 't-emotive-language',
    name: 'Emotive Language',
    category: 'persuasive-language',
    definitionHtml: 'Word choice deliberately selected to trigger an emotional response rather than a neutral one.',
    effectHtml: 'Bypasses purely rational evaluation of an argument by attaching feeling directly to it.',
    whyAuthorsUseItHtml: 'Persuasive texts use emotive language to make a position feel obviously right (or wrong) before the audience has consciously reasoned about it.',
    exampleQuoteId: null,
    genericExampleHtml: '"This heartless policy abandons our most vulnerable" uses "heartless" and "abandons" to provoke feeling, not just describe the policy.',
    analyticalLanguage: ['the emotively charged', 'provokes … through emotive diction'],
    howToRecogniseHtml: 'Word choices with strong positive or negative connotation, where a neutral synonym was clearly available.',
    commonMistakeHtml: 'Naming emotive language without naming the actual emotion it targets (outrage, pity, fear, pride).',
    confusedWithIds: [],
  },
  {
    id: 't-direct-address',
    name: 'Direct Address',
    category: 'persuasive-language',
    definitionHtml: 'Speaking straight to the audience/reader, often using "you".',
    effectHtml: 'Makes the audience feel personally implicated in the argument rather than an observer of it.',
    whyAuthorsUseItHtml: 'Collapses the distance between speaker and audience, useful when the writer wants the audience to feel responsible or included.',
    exampleQuoteId: null,
    genericExampleHtml: '"You know this is wrong" places the claim directly onto the listener rather than a general "one" or "we".',
    analyticalLanguage: ['directly addresses', 'implicates the audience through'],
    howToRecogniseHtml: 'Second-person pronouns ("you", "your") aimed at the reader/listener specifically.',
    commonMistakeHtml: 'Confusing direct address with inclusive language ("we"/"us") — direct address singles the audience out; inclusive language folds the speaker in with them.',
    confusedWithIds: ['t-inclusive-language'],
  },
  {
    id: 't-inclusive-language',
    name: 'Inclusive Language',
    category: 'persuasive-language',
    definitionHtml: 'Language that groups speaker and audience together, typically through "we"/"us"/"our".',
    effectHtml: 'Manufactures a sense of shared identity or common cause between speaker and audience.',
    whyAuthorsUseItHtml: 'Makes a position feel like a shared conclusion the audience already holds, rather than one being argued for.',
    exampleQuoteId: null,
    genericExampleHtml: '"We all know what needs to change" assumes and manufactures audience agreement via "we".',
    analyticalLanguage: ['the inclusive pronoun', 'unites speaker and audience through'],
    howToRecogniseHtml: 'First-person plural pronouns ("we", "us", "our") used to fold the audience in with the speaker.',
    commonMistakeHtml: 'Missing that inclusive language can be manipulative — it manufactures agreement rather than earning it through argument.',
    confusedWithIds: ['t-direct-address'],
  },

  // ---- Narrative / textual ----
  {
    id: 't-motif',
    name: 'Motif',
    category: 'symbolism-and-motif',
    definitionHtml: 'A recurring element (image, phrase, or idea) that develops meaning across a text through repetition.',
    effectHtml: 'Tracks the development of an idea over time, rather than fixing a single meaning at one moment.',
    whyAuthorsUseItHtml: 'Lets a writer trace how an idea changes as the narrative progresses, rather than asserting it once.',
    exampleQuoteId: null,
    genericExampleHtml: 'The recurring glass paperweight motif tracks Winston\'s relationship with the past and its eventual, literal shattering.',
    analyticalLanguage: ['the recurring motif of', 'develops across the text through'],
    howToRecogniseHtml: 'The same image or idea reappears at multiple, separated points — trace it across at least two moments to call it a motif, not a single symbol.',
    commonMistakeHtml: 'Using "motif" and "symbolism" interchangeably — a motif is defined by its recurrence and development; a symbol can be a single instance.',
    confusedWithIds: ['t-symbolism'],
  },
  {
    id: 't-tone',
    name: 'Tone',
    category: 'narrative-voice',
    definitionHtml: "The narrator's or speaker's attitude toward the subject, conveyed through word choice and sentence construction.",
    effectHtml: 'Shapes how the reader is meant to feel about events even when the plot facts alone are neutral.',
    whyAuthorsUseItHtml: 'Tone lets a writer editorialise on events without ever making an explicit judgment statement.',
    exampleQuoteId: 'e-worst-thing',
    genericExampleHtml: null,
    analyticalLanguage: ['the clinical/detached/menacing tone of', 'is coloured by a tone of'],
    howToRecogniseHtml: 'Ask: does the word choice feel warm, cold, sarcastic, clinical, mournful? That felt quality is the tone.',
    commonMistakeHtml: 'Confusing tone (attitude conveyed through language) with mood (the atmosphere/feeling created for the reader) — related, but not the same thing.',
    confusedWithIds: [],
  },

  // ---- Visual and multimodal (unseen texts) ----
  {
    id: 't-framing-composition',
    name: 'Framing & Composition',
    category: 'visual-and-multimodal',
    definitionHtml: 'How elements are arranged within a visual text\'s frame — what is central, cropped, foregrounded or backgrounded.',
    effectHtml: 'Directs the viewer\'s eye and signals relative importance without a single word of text.',
    whyAuthorsUseItHtml: 'Composers of visual texts control meaning through arrangement the same way writers control it through word choice.',
    exampleQuoteId: null,
    genericExampleHtml: 'Placing a single figure small within a vast, empty frame composes them as isolated or powerless.',
    analyticalLanguage: ['is framed to', 'the composition positions', 'foregrounds/backgrounds'],
    howToRecogniseHtml: 'Describe what is placed where in the frame, and what is left out or pushed to the edge.',
    commonMistakeHtml: 'Describing what is IN an image without describing HOW it\'s arranged — composition is about arrangement, not just content.',
    confusedWithIds: ['t-salience-gaze'],
  },
  {
    id: 't-salience-gaze',
    name: 'Salience, Gaze & Vectors',
    category: 'visual-and-multimodal',
    definitionHtml: "What draws the eye first (salience), where a depicted figure's eyes point (gaze), and the implied lines of action/movement (vectors).",
    effectHtml: 'Controls the order in which a viewer processes a visual text and who/what it positions as active versus observed.',
    whyAuthorsUseItHtml: 'Lets a composer direct attention and imply relationships (who is looking at whom, who is acting on whom) without narration.',
    exampleQuoteId: null,
    genericExampleHtml: 'A brightly lit figure at the centre of the frame (high salience) making direct eye contact with the viewer (direct gaze) positions them as demanding the viewer\'s attention.',
    analyticalLanguage: ['is made salient through', 'the direct/averted gaze of', 'the vector created by'],
    howToRecogniseHtml: 'Ask what your eye lands on first (salience), which way any depicted eyes are looking (gaze), and what implied lines of movement connect elements (vectors).',
    commonMistakeHtml: 'Naming "gaze" without saying whether it is direct (at the viewer) or indirect (at something else in-frame) — the direction is the whole point.',
    confusedWithIds: ['t-framing-composition'],
  },
  {
    id: 't-colour-symbolism',
    name: 'Colour Symbolism',
    category: 'visual-and-multimodal',
    definitionHtml: 'The deliberate use of colour to carry symbolic or emotional meaning in a visual text.',
    effectHtml: 'Communicates mood or association instantly and pre-verbally.',
    whyAuthorsUseItHtml: 'Colour carries cultural association (red/danger, blue/calm) that a composer can use or subvert.',
    exampleQuoteId: null,
    genericExampleHtml: 'A poster rendered entirely in cold greys and blues, with a single figure in warm red, uses colour to isolate that figure as the emotional focus.',
    analyticalLanguage: ['the symbolic use of colour', 'is rendered in … tones to suggest'],
    howToRecogniseHtml: 'Note the dominant colour palette and any colour that stands out from it, then ask what association that colour typically carries.',
    commonMistakeHtml: 'Assuming a colour\'s meaning is universal — check whether the text itself establishes or subverts the expected association.',
    confusedWithIds: [],
  },
]
